# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170108_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kirrurl',
            old_name='activate',
            new_name='active',
        ),
    ]
